### PR TITLE
Any word is toggleable and other small changes

### PR DESCRIPTION
**Pull request by certainlyakey**
1. Words are searched for within the current line without taking into account word boundaries. This allows to toggle complex words such as `rgb(255,255,255)` to `hsla(0,50%,100%,1)` without a need to select anything. The only problem here is that the order of switching words is not original (if user dictionary contains a word group such as `[1,12,130]`, they will switch in order of descending char length, that is `[130,12,1]`). I'm still solving this puzzle (related to `re.finditer` not being able to find overlapping regions).
2. I decided to remove words hardcoded in the plugin file and moved them to default settings file.
3. Readme had a handful of typos or old stuff, corrected that.
4. Due to a typo it was not possible to open default settings file from menu, fixed.
5. Toggle Word**s** was made the normalized variant of name. It's now used everywhere instead of Toggle Word (without _s_), except `toggle_word` command to be compatible with already assigned custom shortcuts or macros.

### CODE REVIEW

**Comment by gordio** [comment]
2. - Why?

2, 5 - Create Package Control Message about this changes.

**Comment by certainlyakey** [comment]
1. Sorry for being not clear with this proposal. Say, you want to switch different notations of colors. RGB, HSL and hex notations consist of multiple words. The toggle from `white` to `rgb(255,255,255)` will work, but toggle from `rgb(255,255,255)` to the next notation won't, because only the word cursor is in will count (`rgb` or `255`). I tried to solve this by preselecting the next toggle if it spans several words, but this proved a non stable solution, and it still will not allow togglng initial definition consisting of multiple words without selecting it.
2. & 5. OK, I'll try to do that.

**Comment by certainlyakey** [comment]
Did it. Maybe the number of steps required due to changes in internal names is a bit too much for users...

**Comment by gordio** [comment]
Good work!
Please, add to this message info about changes.

Maybe need bump Version 3? What you think? How about progress with rgb(a)/hsl(a)?

**Comment by certainlyakey** [comment]
That's completely up to you. Is this change big enough? Regarding rgba/hsla, do you mean is it possible to add more different variants of color notations?

**Comment by gordio** [comment]
Ok. Eem.. Nevermind.

**Pull request merged**
